### PR TITLE
Forward vectorization

### PR DESCRIPTION
**Pull request by ChabaneAmaury**
Hello,

I modified the fem_forward logic to make it capable of working with vectorization. On my computer, it changed the computation time for a 64 electrodes reconstruction from ~40s down to ~15s. It is quite an improvement, and it does allow the user to choose between the regular methods or the new ones, through a single argument in "solve_eit". I ran my tests on your given example (eit_static_jac), and the results are the same between the two possibilities. I spent a lot of time working on the improvement of the algorithms, and you will find each time the previous version (yours) commented out, with the new version (mine) just above.

Docstring is up-to-date and each method, when an entirely new one is required, has the same name as the original, followed by "_nd" (for ndarray). I tried as much as possible to use only the numpy's ufuncs, though sometimes it was hardly possible. I also ran some tests to find out what was the best optimization when it comes to computational cost, and the one I have come up with is for now the best you could have (I would need a lot more time).

Feel free to contact me if you need me.

### CODE REVIEW

**Comment by ChabaneAmaury** [comment]
> Thank you! I think we should add some test suite for testing these numerical codes :)
> 
> You can run `black` and `flake8` to correct the linting warnings before merging.

How do I do this? I never used them before, and I would not like to break things :/

**Comment by ChabaneAmaury** [comment]
Moreover, testing the numerical codes will be hard to get, since I found out that the exact same use case can lead to slightly different computation results, which then result in an assertion error when comparing both matrices (regular and vectorized), though even with 2 regulars the problem is the same. My tests (not 100% scientific unfortunately), were to run the new code (from the test branch) and the old code (from the main branch) and then compare the 2 reconstruction polygon by polygon. Turns out they are the exact same, but still got different matrices. I even tried to call first the regular method for constructing the mesh and simulating the measures, then call the vectorized version for reconstruction only, and it works like a charm as well.
I am unsure why it gives us different matrices (my theory would be some very low level differences for float computation).

**Comment by liubenyuan** [comment]
There is a black lint warning.

Yes, I am thinking of using a simple mesh, for example 4 nodes and 2 elements, as the test input. I will try if this assertation works.

**Comment by liubenyuan** [comment]
The result of `eit_static_jac.py` is incorrect with respect to e6894ca
@ChabaneAmaury

**Comment by liubenyuan** [comment]
fixed #35

**Comment by liubenyuan** [comment]
Squash and merge all commits into one.

**Comment by ChabaneAmaury** [comment]
> Squash and merge all commits into one.

What do you mean? Everything is already merged

**Comment by liubenyuan** [comment]
> > Squash and merge all commits into one.
> 
> What do you mean? Everything is already merged


Yes, I plan to manage all the commits in a monotonical way. I combine all your commits into one and prepare for next conda release.

**Comment by liubenyuan** [comment]
I am sorry that I messed up with your commits. Could you please create a new pull request featuring all you vectorized improvements into one commit? @ChabaneAmaury

**Comment by liubenyuan** [comment]
I am drafting a new release featuring your contributions on vectorized forward computation. I tried to manage the commits in a monotalical way so that the changes in each feature is readable in a single commit.

Thank you for your contribution!

**Pull request merged**
