### PR TITLE
Issue setup

### PR DESCRIPTION
**Pull request by DavidMetzIMT**
Hy @liubenyuan,

I work on the note that I made about the setup() in previous issue https://github.com/liubenyuan/pyEIT/pull/42#issuecomment-1106197418 

I hope it fits you
See you

### CODE REVIEW

**Comment by liubenyuan** [comment]
Hi, I've been considering the `setup` things.

We should move the inverse related computation code out of or as an option for forward computing:
  1. `b_matrix` and `smear` should be moved to BP code and check that `b_matrix` is not being used by other imaging algorithms.
  2. `jac` should be calculated when necessary. Jacobian calculation is time consuming, and calculate it in large scale 3D models is not feasible. So we should add an option to `solve`, calculate and returns jacobian when user do want it.
  3. notes should be added to force the user run `setup()` before applying a reconstruction algorithm.

**Comment by liubenyuan** [comment]
Your commits are nearly the same as these requests! Moving `jac` and `B` out of `solve_eit` will ease the calculation using a 3D head model.

**Comment by DavidMetzIMT** [comment]
Hy,

> We should move the inverse related computation code out of or as an option for forward computing:

I think we let it in fwd but add special method for computing what is needed!

>     1. `b_matrix` and `smear` should be moved to BP code and check that `b_matrix` is not being used by other imaging algorithms. These two matrix can be calculated afterwards given `f` and `f[el_pos]`.
>     2. **`jac` should be calculated when necessary.** Jacobian calculation is time consuming, and calculate it in large scale 3D models is not feasible. So we should add an option to `solve` or `solve_eit` (considering change the names?), calculate and returns jacobian when user do want it.

I think we can do that and reduce the responsability of `solve` and `solve_eit` which compute to much things (f, jac_i) and (v, jac, b)
- `solve` should only compute potential distribution and only return f
in all example scripts you only use f, _ = fwd.solve(...)
- `solve_eit`  should only compute voltage meas (simulate) and only return v
in all example scripts you only res.v from res = fwd.solve_eit(...)

However this means that it will break back compatibility and this should be noticed in next tag to users....
Should I do that? 

For the calculation of the Jacobian and the b_matrix i though to introduce:
- `compute_jac` and `compute_b_matrix` which only jac or b_matrix. These methods can be direct be used in EitSolver to compute only the matrix we need and avoid inutile computation!

>     3. notes should be added to force the user run `setup()` before applying a reconstruction algorithm.

I already add a method who raise an error for that purpose!  this method is tahen use in all solving method which need the solver to be initializated...

```
def _check_solver_is_ready(self) -> None:
        """
        Check if solver is ready for solving

        Addtionaly test also if self.H not `None`

        Raises
        ------
        SolverNotReadyError
            raised if solver not ready
        """
        if not self.is_ready or self.H is None:
            msg = "User must run solver.setup() before using solver.solve()"
            raise SolverNotReadyError(msg)
```

> I saw that you have started a branch on this. So could you handle these modifications as well? I will write the test codes for `jac` and `bp` to make the modification to them consistent.

if you'r done push it so that I can use it!

I will get back when I'm done!

**Comment by liubenyuan** [comment]
Sure, let's do it and move a minor revision number.

  1. `solve` calculate voltages distribution. We can drop the `la.inv` and using `sp.solve`, and do not convert the sparse matrix (K) to dense matrix. So that we can handle large FEM models.
  2. `solve_eit` calculate the measurement protocol (boundary voltage differences).
  3. `compute_jac` calculate the jacobian for `jac` and `greit` and `compute_b` calculate the smearing matrix for `bp`. In this way, we can use a much smaller or coarse mesh models for doing EIT imaging.
  4. I check the examples, they are all related to boundary voltages and calls `solve_eit` (except for some forward codes which relies on `solve`).

I am writing test code and these codes are on the `testsuite` branch. The test code should adapt to new `fem.solve` and `fem.solve_eit` apis and to your modifications.

**Comment by DavidMetzIMT** [comment]
Ok i will prepare it!

but:
>We can drop the `la.inv` and using `sp.solve`, and do not convert the sparse matrix (K) to dense matrix. So that we can handle large FEM models.

I do not really get what and how you what to do it!
We cann maybe to about it after I made some new commits!

**Comment by DavidMetzIMT** [comment]
Hy,
I made some modification and tested fem withyour tests in tests_fem (only for jac I had to ajaust it!)
I also tested some of the examples! But I think I will have a look on monday again!
see you

**Comment by liubenyuan** [comment]
> Ok i will prepare it!
> 
> but:
> 
> > We can drop the `la.inv` and using `sp.solve`, and do not convert the sparse matrix (K) to dense matrix. So that we can handle large FEM models.
> 
> I do not really get what and how you what to do it! We cann maybe to about it after I made some new commits!

Hi, I mean this line:
https://github.com/liubenyuan/pyEIT/blob/eebca7f9fc6b25de4fa57c302facb365b5273d93/pyeit/eit/fem.py#L204
When we use `solve` or `solve_eit` for calculating nodes potentials, the coefficients matrix K needs not be inversed (this saves a lot mem requirements and accelerate sparse solver), and also in this line:
https://github.com/liubenyuan/pyEIT/blob/eebca7f9fc6b25de4fa57c302facb365b5273d93/pyeit/eit/fem.py#L210
can be replaced by `sp.solve(K, b)` rather than $K^{-1}b$ per excitation pattern.

**Comment by liubenyuan** [comment]
Thank you. I will check and merge your work at 05/05 (we are on a vocation of international labors day).

**Comment by DavidMetzIMT** [comment]
Ok I understand
so you mean something like that

```
kg = assemble(ke, self.tri, perm, self.n_pts, ref=self.ref_el)
b = self._natural_boundary(ex_mat)
f= scipy.linalg.solve(kg, b) # something like that?
```
(sp means? scipy.linalg?)

but for the calculation of jac `r_matrix = la.inv(kg)` is still needed! or I'm wrong?

**Comment by liubenyuan** [comment]
> Ok I understand so you mean something like that
> 
> ```
> kg = assemble(ke, self.tri, perm, self.n_pts, ref=self.ref_el)
> b = self._natural_boundary(ex_mat)
> f= scipy.linalg.solve(kg, b) # something like that?
> ```
> 
> (sp means? scipy.linalg?)
> 
> but for the calculation of jac `r_matrix = la.inv(kg)` is still needed! or I'm wrong?

Yes, `scipy.linalg`. Jac still need r_matrix, but we can calculate inv(k) and jac using a much smaller mesh.

**Comment by liubenyuan** [comment]
If this feature set is finalized, feel free to notify me.

**Comment by DavidMetzIMT** [comment]
Yes I think it is now ok!

**Pull request merged**
